name: Deploy Pneumonia Detection API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          cd backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug - List files before zipping
        run: |
          cd backend
          echo "=== Files in backend directory ==="
          ls -la
          echo "=== Content of requirements.txt ==="
          head -10 requirements.txt
          echo "=== Content of main.py (first 20 lines) ==="
          head -20 main.py
          
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../backend.zip . -x venv/\* __pycache__/\* .pytest_cache/\* .git/\* .gitignore
          echo "=== Zip file created, checking contents ==="
          unzip -l ../backend.zip | head -30

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip backend.zip
          echo "=== Files after unzipping ==="
          ls -la
          echo "=== Checking if requirements.txt exists ==="
          if [ -f requirements.txt ]; then
            echo "✅ requirements.txt found"
            head -5 requirements.txt
          else
            echo "❌ requirements.txt NOT found"
          fi

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'pneumonia-detection-api-shaista'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
