# .github/workflows/backend-deploy.yml

name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:  
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Zip artifact for deployment
      
      run: |
        cd backend
        zip -r ../backend-release.zip . -x "*.git*" "*__pycache__*" "*.pyc" "venv/*"

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Unzip artifact for deployment
      run: unzip backend-release.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'pneumonia-detection-api-shaista'
        slot-name: 'Production'
        package: .
        startup-command: 'uvicorn main:app --host 0.0.0.0 --port 8000'
