name: Deploy Pneumonia Detection API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create deployment package
        run: |
          echo "Creating deployment package from backend directory..."
          # Create a fresh deployment directory
          mkdir -p deployment_package
          
          # Copy everything from backend into the new directory
          cp -r backend/* deployment_package/

          # Verify contents of the package
          echo "Contents of the deployment package:"
          ls -la deployment_package/
          
          # Zip the deployment package
          cd deployment_package
          zip -r ../pneumonia-app.zip .
          cd ..
          echo "pneumonia-app.zip created."

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: pneumonia-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Extract deployment package
        run: |
          echo "Extracting ZIP file to 'extracted/' directory..."
          unzip pneumonia-app.zip -d extracted/
          echo "Extracted files:"
          ls -la extracted/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pneumonia-detection-api-shaista'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: 'extracted' # The 'package' parameter MUST point to the directory containing the unzipped files.
