# This workflow deploys a Python FastAPI application to Azure App Service.
# It is triggered on every push to the 'main' branch.

name: Deploy to Azure App Service

# Controls when the workflow will run.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # This job contains a sequence of steps.
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # Step 2: Logs in to Azure using the secret stored in your GitHub repository.
      # You MUST create a service principal and add its credentials as a GitHub secret.
      # See the instructions at the end of this document.
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploys the application to the Azure App Service.
      # This action automatically zips the contents of your repository and deploys it.
      # The startup-command parameter has been removed to let Oryx handle it automatically.
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          # The name of your Azure App Service.
          app-name: 'pneumonia-detection-api-shaista'
          # The package to be deployed (the entire repository).
          package: '.'
